### ISSUE TITLE
Connection to BotWaRz server

### ISSUE THREAD

**Issue by substanc3-dev** [madmaxoft/EsetBotWarz#1]
Hi, Im failing to get any response from the Esets BotWarz server... Do you have the same problem, too?

**Comment by madmaxoft** [comment]
Ahoj,
esi to zkousis z firemni site, tak ti to nepujde, musis zvenku :)

**Comment by madmaxoft** [comment]
I've seen such behavior when the connection is made from some specific networks, no idea what's going on, but I expect it to be a server-side issue.
